dependencies:
  dart-xml:
      git: git://github.com/prujohn/dart-xml.git
  Buckshot:
      git: git://github.com/prujohn/Buckshot.git
  dartflash:
      git: git://github.com/bp74/dartflash.git
  mongo-dart:
      git: git://github.com/vadimtsushko/mongo-dart.git
  json-object:
      git: git://github.com/chrisbu/dartwatch-JsonObject.git
  unittest:
      sdk: unittest